server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: weather-push
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weather?characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    # password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.scheduler.instance-id: AUTO
      org.quartz.scheduler.instance-name: weather_scheduler
      org.quartz.job-store.class: org.quartz.impl.jdbcjobstore.JobStoreTX
  # 缓存
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true
      use-key-prefix: true
      key-prefix: cache_

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  expiration: 7200
  tokenHeader: token
  tokenHead: Bearer

# 和风天气
hf-weather:
  base-url: https://devapi.qweather.com
  # 城市搜索
  city-url: https://geoapi.qweather.com/v2/city/lookup?range=cn&location=cityName&key=${hf-weather.key}&number=1

holiday:
  url: https://cdn.jsdelivr.net/gh/NateScarlet/holiday-cn@master

swagger:
  enable: true
