server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: weather-push
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weather?characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    # password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.scheduler.instance-id: AUTO
      org.quartz.scheduler.instance-name: weather_scheduler
      org.quartz.job-store.class: org.quartz.impl.jdbcjobstore.JobStoreTX
  # 缓存
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true
      use-key-prefix: true
      key-prefix: cache_

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  secret:
  expiration: 7200
  tokenHeader: token
  tokenHead: Bearer

#企业微信
qywx:
  corpid:
  push-secret:
  other-secret:
  agentid:
  domain: https://qyapi.weixin.qq.com
  # 获取token
  token-url: ${qywx.domain}/cgi-bin/gettoken?corpid=${qywx.corpid}&corpsecret=SECRET
  # 发送消息
  send-url: ${qywx.domain}/cgi-bin/message/send?access_token=ACCESS_TOKEN
  tag:
    # 创建标签
    create-url: ${qywx.domain}/cgi-bin/tag/create?access_token=ACCESS_TOKEN
    # 获取标签
    list-url: ${qywx.domain}/cgi-bin/tag/list?access_token=ACCESS_TOKEN
    delete-url: ${qywx.domain}/cgi-bin/tag/delete?access_token=ACCESS_TOKEN&tagid=TAG_ID
    add-tag-user-url: ${qywx.domain}/cgi-bin/tag/addtagusers?access_token=ACCESS_TOKEN
    del-tag-user-url: ${qywx.domain}/cgi-bin/tag/deltagusers?access_token=ACCESS_TOKEN
  member:
    # 获取加入企业二维码
    join-qrcode-url: ${qywx.domain}/cgi-bin/corp/get_join_qrcode?access_token=ACCESS_TOKEN
    # 获取部门成员 department_id：获取的部门id（1-根部门）； fetch_child：是否递归获取子部门下面的成员：1-递归获取，0-只获取本部门
    simple-list-url: ${qywx.domain}/cgi-bin/user/simplelist?access_token=ACCESS_TOKEN&department_id=1&fetch_child=1
    tag-member-list: ${qywx.domain}/cgi-bin/tag/get?access_token=ACCESS_TOKEN&tagid=TAGID

#和风天气
hfweather:
  key:
  domain: https://devapi.qweather.com
  #实时天气
  get-url: ${hfweather.domain}/v7/weather/now?location=code&key=${hfweather.key}
  #城市信息
  city-url: https://geoapi.qweather.com/v2/city/lookup?range=cn&location=cityName&key=${hfweather.key}&number=1
  #24h天气
  hour-url: ${hfweather.domain}/v7/weather/24h?location=code&key=${hfweather.key}
  # 穿衣指数  type=3
  index-url: ${hfweather.domain}/v7/indices/1d?type=3&location=code&key=${hfweather.key}
  # 天气预警
  warn-url: ${hfweather.domain}/v7/warning/now?location=code&key=${hfweather.key}
  # 3天天气
  day-url: ${hfweather.domain}/v7/weather/3d?location=code&key=${hfweather.key}

holiday:
  url: https://cdn.jsdelivr.net/gh/NateScarlet/holiday-cn@master

swagger:
  enable: true
