spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weather?characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1 # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: root # Redis服务器连接密码（默认为空）
      timeout: 3000ms # 连接超时时间（毫秒）

sa-token:
  # jwt秘钥
  jwt-secret-key: ENC(URi+96d9EfoiC7IY3QuAkb2Z03mgZP/NV0Qlmn+CoVLrMCoJW31zk++qDKokO1yHv8h+dq0LOWL9EiaQUjPMXw==)
  # 打印日志
  is-log: true

qywx:
  corpid: ENC(h1ThubkA8YcnboOGLwaO05SUJuDwsA79AX8mxBIEo+X6uYDnA+yoCzapA2Dm5DP+n75h8mJRp5Y2kWvsaVkO5Q==)
  push-secret: ENC(wzcvVqXwrh0z1lQ8YIWpBfOWsJ5Udv/Wkb9onqN82+20Y8GeYyJkbfCbJi3CPl8gV4/BjjwDyBU0EOQekj8TptAskrOk26QYetW0MjnJSPw=)
  other-secret: ENC(rpj8eSYkt9+nSjCt/ytCE3j7jKp3u0Bul5QQchSIsZCG8VqljKRqk+wi6fXvDVlsb+wOyDzHsI6PU7anJGnkdcQqHyHcHZOkY5/vBe2/xDI=)
  agentid: ENC(H+7T49cJ0hrwQ01oFriXV2+h2sDFVDM40OpoACyVktKpzEbYUYZI0PqIi0q6jYA4)
  member-url: http://localhost:9528/admin/member/member

hf-weather:
  key: ENC(E8D+neLnWOjo4L5zxztNhVH6eqPrMUFuFIn8PLrY8n+4AjWfVux+JmVoQ4XroGHRJy/4nWqO6I8tT6fS1aNgciJfwOGuplOPN2URzvlXq1U=)