spring:
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.scheduler.instance-id: AUTO
      org.quartz.scheduler.instance-name: weather_scheduler
      org.quartz.job-store.class: org.quartz.impl.jdbcjobstore.JobStoreTX

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token前缀（注意前缀+空格+token）
  token-prefix: Bearer
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # 关闭cookie
  is-read-cookie: false

#企业微信
qywx:
  base-url: https://qyapi.weixin.qq.com/cgi-bin

# 和风天气
hf-weather:
  base-url: https://devapi.qweather.com
  # 城市搜索
  city-url: https://geoapi.qweather.com

holiday:
  url: https://cdn.jsdelivr.net/gh/NateScarlet/holiday-cn@master

# springdoc-openapi项目配置
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yh.weatherpush.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  # 开启增强配置
  enable: true

# 访问白名单
white-list:
  - /admin/login
  - /error
  - /holidays/**