spring:
  datasource:
    url: jdbc:mysql://192.168.3.3:3306/weather?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 192.168.3.3 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    timeout: 3000ms # 连接超时时间（毫秒）

jwt:
  secret:
  expiration: 7200
  tokenHeader: token
  tokenHead: Bearer

qywx:
  corpid:
  push-secret:
  other-secret:
  agentid:

hfweather:
  key:

swagger:
  enable: true